# This rule is not used by the project mutating-registry-webhook itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dev.dev.flemzord.fr.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mutating-registry-webhook
    app.kubernetes.io/managed-by: kustomize
  name: registryrewriterule-admin-role
rules:
- apiGroups:
  - dev.dev.flemzord.fr
  resources:
  - registryrewriterules
  verbs:
  - '*'
- apiGroups:
  - dev.dev.flemzord.fr
  resources:
  - registryrewriterules/status
  verbs:
  - get
