name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  KIND_VERSION: v0.20.0
  KUBERNETES_VERSION: v1.28.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run golangci-lint
        run: make lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run tests
        run: |
          go mod download
          make test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./cover.out

  manifests:
    name: Verify Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Generate manifests
        run: make manifests

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes detected. Please run 'make manifests' and commit the changes."
            git diff
            exit 1
          fi

  helm-lint:
    name: Helm Chart Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Install Kubebuilder
        run: |
          curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)"
          chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/

      - name: Generate Helm chart
        run: |
          kubebuilder edit --plugins=helm/v1-alpha

      - name: Lint Helm chart
        run: |
          helm lint dist/chart

      - name: Template Helm chart
        run: |
          helm template test dist/chart

  e2e-kind:
    name: E2E Tests (Kind)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Setup Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind cluster
        run: |
          cat <<EOF | kind create cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            image: kindest/node:${KUBERNETES_VERSION}
          EOF

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
          kubectl wait --for=condition=Available --timeout=300s deployment --all -n cert-manager

      - name: Build and load Docker image
        run: |
          make docker-build IMG=mutating-registry-webhook:e2e
          kind load docker-image mutating-registry-webhook:e2e

      - name: Run E2E tests
        run: |
          make test-e2e

      - name: Collect logs on failure
        if: failure()
        run: |
          echo "=== Controller logs ==="
          kubectl logs -n mutating-registry-webhook-system deployment/mutating-registry-webhook-controller-manager || true
          echo "=== Events ==="
          kubectl get events --all-namespaces --sort-by='.lastTimestamp' || true

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
